---
galaxy_info:
  author: Osamu Nagano
  description: To setup Unbound server.
  license: BSD-3-Clause or MIT
  min_ansible_version: 2.8
  platforms:
  - name: EL
    versions:
    - 8
  galaxy_tags: []
dependencies:
  - role: git
    vars:
      git_repo: "{{ unbound_data.pull_url }}"
      git_version: "{{ unbound_data.version }}"
      git_config_ssl_verify: false
